version: '3.3'

services:
  redis:
    image: library/redis
    hostname: redis
    deploy:
      mode: replicated
      replicas: 1

  zmc-ldap:
    image: '${DOCKER_REPO_NS}/zmc-ldap:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-ldap'
    build:
      context: '.'
      dockerfile: 'ldap/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-ldap:${DOCKER_CACHE_TAG}' ]
      args:
         DOCKER_REPO_NS: '${DOCKER_REPO_NS}'
         DOCKER_BUILD_TAG: '${DOCKER_BUILD_TAG}'
    volumes:
      - ${LOCAL_SRC_DIR}:/code
      - build:/build
    configs:
      - domain_name
    secrets:
      - ca.key
      - ca.pem
      - ldap.key
      - ldap.crt
      - ldap.master_password
      - ldap.root_password
      - ldap.replication_password
      - ldap.postfix_password
      - ldap.amavis_password
      - ldap.nginx_password

  zmc-mta:
    image: '${DOCKER_REPO_NS}/zmc-mta:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-mta'
    build:
      context: '.'
      dockerfile: 'mta/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-mta:${DOCKER_CACHE_TAG}' ]
      args:
         DOCKER_REPO_NS: '${DOCKER_REPO_NS}'
         DOCKER_BUILD_TAG: '${DOCKER_BUILD_TAG}'
    volumes:
      - ${LOCAL_SRC_DIR}:/code
    configs:
      - av_notify_email
      - zimbra_ldap_userdn
    secrets:
      - ca.key
      - ca.pem
      - mta.key
      - mta.crt
      - ldap.master_password
      - ldap.root_password
      - ldap.postfix_password
      - ldap.amavis_password

  zmc-mailbox:
    image: '${DOCKER_REPO_NS}/zmc-mailbox:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-mailbox'
    build:
      context: '.'
      dockerfile: 'mailbox/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-mailbox:${DOCKER_CACHE_TAG}' ]
      args:
         DOCKER_REPO_NS: '${DOCKER_REPO_NS}'
         DOCKER_BUILD_TAG: '${DOCKER_BUILD_TAG}'
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - ${LOCAL_SRC_DIR}:/code
      - blobvolume:/opt/zimbra/store
      - tmpvolume:/opt/zimbra/data/tmp
    configs:
      - domain_name
      - admin_account_name
      - spam_account_name
      - ham_account_name
      - virus_quarantine_account_name
      - gal_sync_account_name
      - tzdata_area
      - tzdata_zone
      - time_zone_id
    secrets:
      - ca.key
      - ca.pem
      - mailbox.key
      - mailbox.crt
      - ldap.master_password
      - ldap.root_password
      - mysql.password
      - admin_account_password
      - spam_account_password
      - ham_account_password
      - virus_quarantine_account_password

  zmc-mysql:
    image: '${DOCKER_REPO_NS}/zmc-mysql:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-mysql'
    build:
      context: '.'
      dockerfile: 'mysql/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-mysql:${DOCKER_CACHE_TAG}' ]
      args:
         DOCKER_REPO_NS: '${DOCKER_REPO_NS}'
         DOCKER_BUILD_TAG: '${DOCKER_BUILD_TAG}'
    volumes:
      - ${LOCAL_SRC_DIR}:/code
    secrets:
      - mysql.password

  zmc-proxy:
    image: '${DOCKER_REPO_NS}/zmc-proxy:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-proxy'
    build:
      context: '.'
      dockerfile: 'proxy/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-proxy:${DOCKER_CACHE_TAG}' ]
      args:
         DOCKER_REPO_NS: '${DOCKER_REPO_NS}'
         DOCKER_BUILD_TAG: '${DOCKER_BUILD_TAG}'
    volumes:
      - ${LOCAL_SRC_DIR}:/code
    secrets:
      - ca.key
      - ca.pem
      - proxy.key
      - proxy.crt
      - ldap.master_password
      - ldap.root_password
      - ldap.nginx_password
    ports:
      - '8080:80'
      - '8443:443'
      - '8071:7071'
      - '8000:5000'
      - '9071:9071'

  zmc-solr:
    image: '${DOCKER_REPO_NS}/zmc-solr:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-solr'
    build:
      context: '.'
      dockerfile: 'solr/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-solr:${DOCKER_CACHE_TAG}' ]
    environment:
      - SOLR_MODE=standalone
      - SOLR_MEMORY=1g
    ports:
      - "8983:8983"

  zmc-test:
    image: '${DOCKER_REPO_NS}/zmc-test:${DOCKER_BUILD_TAG}'
    hostname: 'zmc-test'
    build:
      context: '.'
      dockerfile: 'test/Dockerfile'
      cache_from: [ '${DOCKER_REPO_NS}/zmc-test:${DOCKER_CACHE_TAG}' ]
    configs:
      - domain_name
    depends_on:
      - zmc-proxy
    entrypoint:
      - /zimbra/init
      - --shutdown
      - "no"
    environment:
      ADMIN_PORT: "9071"
      HTTPS_PORT: "443"
      SOAPSERVICE_PORT: "8443"
    secrets:
      - admin_account_password


secrets:
   ca.key:
     file: ./.keystore/ca.key
   ca.pem:
     file: ./.keystore/ca.pem
   ldap.key:
     file: ./.keystore/ldap.key
   ldap.crt:
     file: ./.keystore/ldap.crt
   mta.key:
     file: ./.keystore/mta.key
   mta.crt:
     file: ./.keystore/mta.crt
   mailbox.key:
     file: ./.keystore/mailbox.key
   mailbox.crt:
     file: ./.keystore/mailbox.crt
   proxy.key:
     file: ./.keystore/proxy.key
   proxy.crt:
     file: ./.keystore/proxy.crt
   ldap.master_password:
     file: ./.secrets/ldap.master_password
   ldap.root_password:
     file: ./.secrets/ldap.root_password
   ldap.replication_password:
     file: ./.secrets/ldap.replication_password
   ldap.postfix_password:
     file: ./.secrets/ldap.postfix_password
   ldap.amavis_password:
     file: ./.secrets/ldap.amavis_password
   ldap.nginx_password:
     file: ./.secrets/ldap.nginx_password
   mysql.password:
     file: ./.secrets/mysql.password
   admin_account_password:
     file: ./.secrets/admin_account_password
   spam_account_password:
     file: ./.secrets/spam_account_password
   ham_account_password:
     file: ./.secrets/ham_account_password
   virus_quarantine_account_password:
     file: ./.secrets/virus_quarantine_account_password

configs:
   av_notify_email:
     file: ./.config/av_notify_email
   domain_name:
     file: ./.config/domain_name
   admin_account_name:
     file: ./.config/admin_account_name
   spam_account_name:
     file: ./.config/spam_account_name
   ham_account_name:
     file: ./.config/ham_account_name
   virus_quarantine_account_name:
     file: ./.config/virus_quarantine_account_name
   gal_sync_account_name:
     file: ./.config/gal_sync_account_name
   zimbra_ldap_userdn:
     file: ./.config/zimbra_ldap_userdn
   tzdata_area:
     file: ./.config/tzdata_area
   tzdata_zone:
     file: ./.config/tzdata_zone
   time_zone_id:
     file: ./.config/time_zone_id

volumes:
  blobvolume: {}
  tmpvolume: {}
  build: {}
